apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo
resources:
  - https://github.com/kyverno/kyverno/releases/download/v1.13.2/install.yaml
  - https://projectcontour.io/quickstart/contour-gateway-provisioner.yaml
